import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

import { ApolloClient, InMemoryCache, gql } from '@apollo/client';

export const getServerSideProps = async (context) => {
    const slug = context.params.slug;

    const client = new ApolloClient({
        uri: 'https://localhost:7032/api/graphql',
        cache: new InMemoryCache()
    });

    const { data } = await client.query({
        query: gql`
            query GetBlogPost {
                blogPost(status: PUBLISHED, where: {alias: {alias: "${slug}"}}, first: 1) {
                    author
                    createdUtc
                    displayText
                    alias {
                        alias
                    }
                    markdownBody {
                        html
                    }
                }
            }
        `
    });

    return {
        props: {
            post: data.blogPost[0]
        }
    };
};

export default function Home({ post }) {
  return (
    <div className={styles.container}>
      <Head>
        <title>NextJS Blog with Orchard</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
            {post.displayText}
        </h1>

        <p className={styles.description}>
            By {post.author} at {new Date(post.createdUtc).toLocaleString()}
        </p>

        <div dangerouslySetInnerHTML={{ __html: post.markdownBody.html }} className={styles.grid}>
        </div>
      </main>
    </div>
  )
}
