import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

import { ApolloClient, InMemoryCache, gql } from '@apollo/client';

export const getServerSideProps = async () => {
  // Request data to the backend
  /*
  const httpLink = new HttpLink({ uri: 'https://localhost:7032/api/graphql' });
  const authLink = new ApolloLink((operation, forward) => {
    const token = '';
  
    operation.setContext({
      headers: {
        authorization: token ? `Bearer ${token}` : ''
      }
    });
  
    return forward(operation);
  });

  const client = new ApolloClient({
    link: authLink.concat(httpLink),
    cache: new InMemoryCache()
  });

  const { data } = await client.query({
    query: gql`
      query GetBlogPosts {
        blogPost(status: PUBLISHED) {
          author
          createdUtc
          displayText
        }
      }
    `
  });
  */

  const client = new ApolloClient({
    uri: 'https://localhost:7032/api/graphql',
    cache: new InMemoryCache()
  });

  const { data } = await client.query({
    query: gql`
      query GetBlogPosts {
        blogPost(status: PUBLISHED) {
          author
          createdUtc
          displayText
          alias {
            alias
          }
        }
      }
    `
  });

  return {
    props: {
      posts: data.blogPost
    }
  };
};

export default function Home({ posts }) {
  return (
    <div className={styles.container}>
      <Head>
        <title>NextJS Blog with Orchard</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>

        <p className={styles.description}>
          Get started by editing{' '}
          <code className={styles.code}>pages/index.js</code>
        </p>

        <div className={styles.grid}>
          {posts.map((post) => (
            <a key={post.alias.alias} href={post.alias.alias} className={styles.card}>
              <h2>{post.displayText} &rarr;</h2>
              <p>By {post.author} at {new Date(post.createdUtc).toLocaleString()}</p>
            </a>
          ))}
        </div>
      </main>
    </div>
  )
}
